### PR TITLE
bau branch

### PR DESCRIPTION
**Pull request by theguidon**

### CODE REVIEW

**Comment by theguidon** [comment]
image

- [ ] redo

- follow everything from figma
- create `/archives/` subdirectory
- create `index.html` in `/archives`
- add everything else there, CSS, duplicate logos, etc.
- use HTML only for this one
- header and footer of archives are NOT the same

---

image

- image should not be compressed, use `object-fit: cover`
- each cell is a link:

---

- 2017 (Blue Ballot 2017) - https://issuu.com/theguidonweb/docs/_final__blue_ballot_2017
- 2020 (A Year in Review 2020) - https://issuu.com/theguidonweb/docs/gdn_sanggu_review_1920
- 2021 (Blue Ballot 2021) - https://issuu.com/theguidonweb/docs/blue_ballot_2021
- 2022 (Blue Ballot 2022) - https://issuu.com/theguidonweb/docs/032122-blue_ballot_2022-2
- 2023 (Blue Ballot 2023) - https://blueballot.theguidon.com

just take a screenshot of the cover page or use a placeholder image for now for the thumbnail

---

image

- [ ] fix overflow? avoid using `overflow-x: hidden`
- this might be in `Layout`

---

image

- [ ] fix overflow; avoid using `overflow-x: hidden`
- [ ] logo looks slightly pixelated, redownload bigger file as SVG maybe then use that new one in hero

---

image

- [ ] header should stay fixed to top
- [ ] sidebar and overlay should stay fixed to top

**Comment by luisbauu** [comment]
hello all archives comments addressed 

this one lang i don't understand 
"sidebar and overlay should stay fixed to top"

**Comment by luisbauu** [comment]
i think we should round the images lang? wdyt

**Comment by theguidon** [comment]
- [ ] separate archives. delete it from this repository and add to https://github.com/theguidon/blue-ballot-archives. it should not be referenced at all (except for an anchor tag to `blueballot.theguidon.com/archives`) that is hardcoded.

---

image

- [ ] only route should be `/candidates` and `/candidate/:name` but the one with name can be removed since i told chester to add it also

---

image

**none of the comments from last time were resolved, do not check them yourself**

- [ ] fix overflow
- [ ] fix overlay and sidebar to top of screen

---

- [ ] landing page not done
- [ ] list of candidates page not done

**Comment by theguidon** [comment]
also for the landing page, add states for:

- [ ] final results (available or no)
- [ ] final results (actual numbers)
- [ ] live tweets embed URL (array)

**Comment by theguidon** [comment]
image

- it's the overlay tint that's causing the overflow
- [ ] fix overflow
- [ ] set header and overlay and menu to position fixed to top of screen

---

- [ ] separate archives. delete it from this repository and add to https://github.com/theguidon/blue-ballot-archives. it should not be referenced at all (except for an anchor tag to `blueballot.theguidon.com/archives`) that is hardcoded.

---

image

- [ ] only route should be `/candidates` and `/candidate/:name` but the one with name can be removed since i told chester to add it also

---

- [ ] home page not done
- [ ] landing page not done
- [ ] list of candidates page not done

---

image

- [ ] fix margins left and right
- [ ] increase margin bottom

---

image

- [ ] fix mobile responsiveness (for all, dont use fixed width for the container)

---

image


- [ ] margins/paddings are wrong (left not eq to right?)
- [ ] remove "2023" from "Blue Ballot 2023" -- "Blue Ballot is The GUIDON’s special coverage of the Sanggunian General Elections. Designed and developed by Digital Development 2022-2023."

---

image

- [ ] fix logo not centered

**Comment by theguidon** [comment]
# Home page

image

- [ ] fix mobile responsiveness (margins)
- [ ] article container (image + title + excerpt rectangle) should link to their respective pages

---

image

- [ ] add dummy data (changes layout so we only have to edit a few lines rather than hardcoded)
- [ ] for final results
- [ ] twitter updates
- [ ] infographic available

- basically, if the states/consts/whatever are empty = pre-MDA layout
- if there are values = follow post-MDA layout

---

# All Candidates page

image

- [ ] fix spacing (more space between bar and name)
- [ ] fix: if you remove hover, the text flashes to white then back to black

---

image

- [ ] this isnt the layout for candidates mobile, **redo**

---

# Misc

image

- [ ] fix url, should be `blueballot.theguidon.com/archives`

**Comment by theguidon** [comment]
# Home page

- [ ] editorial still not clickable + linked
- [ ] incumbents still not clickable + linked

---

image

- [ ] margins still not fixed for mobile

---

image

- [ ] add dummy data (changes layout so we only have to edit a few lines rather than hardcoded)
- [ ] for final results
- [ ] twitter updates
- [ ] infographic available

- basically, if the states/consts/whatever are empty = pre-MDA layout
- if there are values = follow post-MDA layout

---

image

- [ ] this isnt the layout for candidates mobile, **redo**

**Comment by theguidon** [comment]
# Home

image

- [ ] fix buttons in mobile; these should be smaller; follow figma

---

image

- [ ] chevron icons should have `cursor: pointer`
- [ ] fix right chevron icon, **again avoid 100vw**
- [ ] fix the candidate list (arrows too close), you can make the images smaller for smaller screens

---

- i love the on hover bg color change tho

**Comment by theguidon** [comment]
image

- [ ] set `max-width` to figma value and `width: 100%` for buttons
- [ ] change href of buttons to `/candidates`

---

image

- [ ] fix arrows?

---

image

- [ ] fix alignment to center

**Comment by theguidon** [comment]
image

- [ ] fix: everything isnt centered

- this is why you avoid 100vw. change ALL instances of `w-screen` to use `width: 100%` instead

---

image

- [ ] fix everything

**Pull request merged**
